### PR TITLE
Update to STIX 2.1

### PR DESCRIPTION
**Pull request by legoguy1000**

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Thank you Alex @legoguy1000 !

**Comment by legoguy1000** [comment]
I tested it locally and it seems to work. We updated our internal project that leverages this library and the new branch appears to provide the same data and functionality as before. Besides that, I can't say any more on breaking changes or if I missed anything.

**Review by Cyb3rWard0g — APPROVED** [review]
Looks good to me following https://github.com/mitre-attack/attack-workbench-taxii-server/blob/main/docs/USAGE.md

**Comment by legoguy1000** [comment]
Will u push an updated version to pypi??

**Comment by Cyb3rWard0g** [comment]
Hey @legoguy1000 ! Yes, I am running all our notebooks in the playground folder in docs. Everything looks good to me too. thank you again! Pushing a new Pip version in a few mins.

**Comment by Cyb3rWard0g** [comment]
Ok Pip package https://pypi.org/project/attackcti/ and repo release ;) https://github.com/OTRF/ATTACK-Python-Client/releases/tag/0.5.4 . Thank you again @legoguy1000 !! :)

**Comment by jondricek** [comment]
hey folks - I just wanted to take a minute to say thank you for updating the library so fast after we turned off the TAXII 2.0 server last week. I had a note to come check in here today and maybe to a pull request, but looks like I didn't have to! I was checking my own fork of your repo from the other month and it looks like the changes here are more comprehensive than my own testing, so well done!

from everyone on the ATT&CK Software Dev team - thank you for updating!

**Comment by legoguy1000** [comment]
> hey folks - I just wanted to take a minute to say thank you for updating the library so fast after we turned off the TAXII 2.0 server last week. I had a note to come check in here today and maybe to a pull request, but looks like I didn't have to! I was checking my own fork of your repo from the other month and it looks like the changes here are more comprehensive than my own testing, so well done!
> 
> from everyone on the ATT&CK Software Dev team - thank you for updating!
> 
> [Edit] And good luck fielding all the "the library isn't working" questions that you'll be getting from people who haven't updated along with us!

We use this library very extensively for our operations and we're not tracking the server deprecation so on the 18th all our stuff just broke. I thought it would be more involved. Luckily the dependent projects were already updated to support 2.1.

**Comment by Cyb3rWard0g** [comment]
> hey folks - I just wanted to take a minute to say thank you for updating the library so fast after we turned off the TAXII 2.0 server last week. I had a note to come check in here today and maybe to a pull request, but looks like I didn't have to! I was checking my own fork of your repo from the other month and it looks like the changes here are more comprehensive than my own testing, so well done!
> 
> from everyone on the ATT&CK Software Dev team - thank you for updating!
> 
> [Edit] And good luck fielding all the "the library isn't working" questions that you'll be getting from people who haven't updated along with us!

Thank you very much @jondricek! It means a lot and I appreciate you taking the time to check. I appreciate all the support and for thinking of us during the migration to 2.1. Also, big thanks to @legoguy1000, for helping with all of it. Love the community support!! Happy holidays and happy new year!!

**Pull request merged**
