### PR TITLE
Added ICS campaigns and some ICS fixes

### PR DESCRIPTION
**Pull request by rubinatorz**
hi @Cyb3rWard0g!

I have added ICS campaigns and complemented the ics_filter_objects with items that were "missing". I know ICS doesn't have tools, but maybe in the future :) And I fixed some typos.

Regards,
Ruben

### CODE REVIEW

**Review by Cyb3rWard0g — APPROVED** [review]
Niceee!! Thank you @rubinatorz ! :)

**Review by Cyb3rWard0g — APPROVED** [review]
🚀 Thank you for taking the time @rubinatorz !

**Comment by Cyb3rWard0g** [comment]
Hello @rubinatorz ! it has been a while since we last spoke. Thank you for taking the time to contribute to the library I will release a new version of the library today

**Comment by Cyb3rWard0g** [comment]
https://pypi.org/project/attackcti/0.3.9/

**Comment by rubinatorz** [comment]
Thanks a lot @Cyb3rWard0g!

I think you can close PR #63 (from someone else), because I noticed that his small change was included in my PR as well.

**Pull request merged**
